### ISSUE TITLE
Not able to perform invoke operations from API

### ISSUE THREAD

**Issue by alejandrolr** [IBM/blockchain-network-on-kubernetes#8]
Hi!!
I've deployed this example in a kubernetes cluster and it worked perfectly. If I perform some invokes/queries inside one peer it works fine. 

However, if I try to perform an invoke operation using the fabcar Node SDK example (https://github.com/hyperledger/fabric-samples/tree/release-1.1/fabcar), configuring properly the peers/orderer/CA directions and chancodes requests, I'm not able to perform invokes (it is strange). 
Although I can enroll, register and query without problem.

Have you tried to use this network using the Node SDK to perform invokes?

Regards!!

**Comment by maheshwarishikha** [comment]
@alejandrolr , very strange that only invoke is not working for you.
It might be because you are taking 1.1 sample...Try once https://github.com/hyperledger/fabric-samples/tree/release-1.0/fabcar as network is also 1.0 version.

**Comment by alejandrolr** [comment]
Thank you considering my question!! But not worked... Ive changed my code to 1.0 version without success (not able to invoke) :( 

Have you connected something using the Node SDK to this cluster to interact properly with the network?

Regards!!!

**Comment by alejandrolr** [comment]
I've fixed the problem!! thank you @maheshwarishikha. The problem was that I was using a cluster with a cos OS (Google) images, I've changed them to Ubuntu and now it works fine!!

**Comment by maheshwarishikha** [comment]
@alejandrolr , thanks for providing the updates on this. Good catch and learning too:)

**Comment by maheshwarishikha** [comment]
Hey @alejandrolr , someone is trying out to invoke/query using NodeSDK example with the network on Kubernetes. Enroll and register is working fine for him but query/invoke is failing with following error:
"Verify() returned x509: certificate signed by unknown authority"
did you face anytime this error? Any idea, how to fix this.

P.S.: I am not able to check this because of some time constraint, so asking if you know the fix.:)
Thanks in advance.
