### ISSUE TITLE
How to make copyartifact Pod run

### ISSUE THREAD

**Issue by Abhinavsai18** [IBM/blockchain-network-on-kubernetes#80]
While following the steps, I got this issue stating "Waiting for container of copy artifact pod to run. Current status of copyartifacts is Succeeded". Please suggest me the solution for this issue.
![WhatsApp Image 2021-05-11 at 4 21 55 PM](https://user-images.githubusercontent.com/75847674/120789714-981c1e80-c54f-11eb-9ce9-00f30448fd4a.jpeg)

**Comment by maheshwarishikha** [comment]
@Abhinavsai18 , for the log messages, it looks like you re-ran without deleting the existing job or say clean up.

Please clean up properly and rerun. This job is copying the artifacts in the container, please check manually whether it is getting copied. Sometimes it gets copied but script could not capture the correct status. It might happen because of kubectl version issue. Please retry and let me know if issue persists. Thanks

**Comment by Abhinavsai18** [comment]
> @Abhinavsai18 , for the log messages, it looks like you re-ran without deleting the existing job or say clean up.
> 
> Please clean up properly and rerun. This job is copying the artifacts in the container, please check manually whether it is getting copied. Sometimes it gets copied but script could not capture the correct status. It might happen because of kubectl version issue. Please retry and let me know if issue persists. Thanks

Thankyou so much. It worked and I've completed first 6 steps in the documentation without any error. Could you please help me in completing the 7th step as I'm unable to find the public IP of my kubernetes cluster and please let me know where the piece of code at the end of step-7 is supposed to be executed. Thankyou again.

**Comment by maheshwarishikha** [comment]
@Abhinavsai18 , Glad to know it worked for you. Answered your follow-up question in another issue, hence closing this one.
